spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true # SQL?? ?? ??? ??? ?? ??, ?? ??? ?? select * From ~~~ ???
        use_sql_comments: false  # JPQL? ?? ??
        # default_batch_fetch_size: 10  # 전역으로 동작하여 ManyToOne에서 발생하는 N+1 문제도 해결됨

logging:
  level:
    root: INFO
    com.ll.jpanplusoneproblemsolveexam: DEBUG  #????
    org.hibernate.orm.jdbc.bind: TRACE # SQL ???? ???(?? ??? ?? ??)
    org.hibernate.orm.jdbc.extract: TRACE #??? ??? ???